### ISSUE TITLE
Issue-Update comment to reflect change to tokenReceived method

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/test#20]
Automated Review Comments
Issues in ABI/ERC223Token.abi:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
Issues in LICENSE:
  - (5, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in PossibleAPI.md:
  - (6, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223.sol:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
Issues in token/ERC223/IERC223.sol:
  - (5, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
Issues in token/ERC223/IERC223Recipient.sol:
  - (28, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
Issues in token/ERC223/README.md:
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in token/ERC223/extensions/ERC223Burnable.sol:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
Issues in token/ERC223/extensions/ERC223Mintable.sol:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
Issues in utils/Address.sol:
  - (11, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
