### ISSUE TITLE
Issue-Filtering is target an address or contract

Added an assembling function to choose if the target is an address or a contract. transfer() is now calling transferToAddress or transferToContract with no more need to filter if the token receiver is a contract in UI!

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/test#6]
Automated Review Comments
Issues in ERC23_token.sol:
  - (4, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
